name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: alpine
    - shell: bash
    env:
    ssh_key: ${{ ssh_key }}
    run: |
      ssh -o StrictHostKeyChecking=no root@5.75.241.59 -i id.rsa "echo 'Test 123'"
